AnimalShelter/AnimalShelter.Solution/Models/AnimalShelter.cs
using System.Collections.Generic;

namespace AnimalShelter.Models
{
  public class Animal 
  {
    //private static List<Animal> _animalInstance = new List<Animal> {};
    public int AnimalId {get; set;}
    public string Type { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
    public string DateOfAdmittance { get; set; }
    public string FavoriteFood { get; set; }

  //  // public Animal(string type)
  //   {

  //     //_animalInstance = new List<Animal> {};
  //    //  Type = type;
      
      
  //   }

  }
}

AnimalShelter/AnimalShelter.Solution/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public DbSet<Animal> Animals { get; set; }

    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/AnimalShelter.Solution/Models/DatabaseConfig.cs
namespace AnimalShelter.Models
{
  public static class DBConfiguration
  {
    public static string ConnectionString { get; set; }
  }
}

AnimalShelter/AnimalShelter.Solution/Controllers/AnimalShelterController.cs
using System.Collections.Generic;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;

namespace AnimalShelter.Controllers
{
    public class AnimalShelterController : Controller
    {
    private readonly AnimalShelterContext _db;

    public AnimalShelterController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.ToList();
      return View(model);
    }

public ActionResult Create()
{
    return View();
}

[HttpPost]
public ActionResult Create(Animal animal)
{
    _db.Animals.Add(animal);
    _db.SaveChanges();
    return RedirectToAction("Index");
}

public ActionResult Details(int id)
{
  Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
  return View(thisAnimal);

}
}
}

AnimalShelter/AnimalShelter.Solution/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

AnimalShelter/AnimalShelter.Solution/Views/AnimalShelter/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4>Add an animal to our shelter:</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Type)
    @Html.TextBoxFor(model => model.Type)
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    @Html.LabelFor(model => model.Age)
    @Html.TextBoxFor(model => model.Age)
    @Html.LabelFor(model => model.DateOfAdmittance)
    @Html.TextBoxFor(model => model.DateOfAdmittance)
    @Html.LabelFor(model => model.FavoriteFood)
    @Html.TextBoxFor(model => model.FavoriteFood)
    <input type="submit" value="Add a new animal" />
}
<p>@Html.ActionLink("Show all animals", "Index")</p>

AnimalShelter/AnimalShelter.Solution/Views/AnimalShelter/Index.cshtml
@{
    Layout = "_Layout";
}

@using AnimalShelter.Models;

<h1>Welcome to the AnimalShelter!</h1>

@if (@Model.Count == 0)
{
  <h3>No animals have been added yet!</h3>
} 


<ul>
@foreach (Animal animal in Model)
  { <li>@Html.ActionLink($"{animal.Type}", "Type of animal", new { id = animal.AnimalId })</li>
      <li>@Html.ActionLink($"{animal.Name}", "Name of animal", new { id = animal.AnimalId })</li>
      <li>@Html.ActionLink($"{animal.Age}", "Age", new { id = animal.AnimalId })</li>
      <li>@Html.ActionLink($"{animal.DateOfAdmittance}", "Date of admittance", new { id = animal.AnimalId })</li>
      <li>@Html.ActionLink($"{animal.FavoriteFood}", "Favorite food", new { id = animal.AnimalId })</li>

  }
</ul>

<p>@Html.ActionLink("Show all animals", "Index", "AnimalShelter")</p>

AnimalShelter/AnimalShelter.Solution/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

<h1>Welcome to the Animal Shelter!</h1>
<p>@Html.ActionLink("See all Animals", "Index", "AnimalShelter")</p>

<p>@Html.ActionLink("Add an animal", "Create", "AnimalShelter")</p>

AnimalShelter/AnimalShelter.Solution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>AnimalShelter</title>
        <link 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
            crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/style.css">
    </head>
    <body>

        <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Placeholder</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        </nav>
    <main>
        <div class="container">
        @RenderBody()
        </div>
    </main>

    </body>
</html>